// aplus_mpvue/src/pages/click/index.vue
<template>
  <div class="event-click" @click.stop="onAplusClk">
    <div class="click-detail">
      <img src="https://gd1.alicdn.com/imgextra/i4/2207297515629/O1CN01W5rDzt1rS89qNHD1f_!!2207297515629.jpg_400x400.jpg"
        alt="">
      <div>
        <p v-for="(item, index) in detail" :key="index">{{ item.name }}: {{ item.value }}</p>
      </div>
    </div>
    <div class="click-purchase">
      <button 
      class="auto_click" 
      type="default" 
      data-name="test_click" 
      data-pagename="test_page" 
     >点击购买(自动)</button>
      <button type="default" @tap="navigateToClick">点击购买(手动)</button>
    </div>
  </div>
</template>

<script>
import '../../utils/aplus';

export default {
  data() {
    return {
      detail: [
        { name: '商品名称', value: '床头灯' },
        { name: '颜色', value: '黄色' },
        { name: '商品ID', value: '003' }
      ]
    }
  },
  components: {
  },
  methods: {
    navigateToClick() {
      console.log('点击事件被触发了')
      wx.qt.record('test_clk', 'CLK', {})
    },
    onAplusClk(e) {
    if (wx) {
      wx.qt_queue.push({
      action: 'qt.qt_pubsub.publish',
      arguments: ['onAplusClk', {
        status: 'ready',
        event: e,
			  context: this
      }]
     })
    } else {

      wx.qt.qt_pubsub.publish('onAplusClk', {
        status: 'ready',
        event: e,
			  context: this
      })
    }
  },

  created() {

  }
}
}
</script>

<style scoped>
.event-click {
  padding: 30px 5%;
}

.click-detail {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  margin: 30px 0 50px;
}

.click-detail img {
  width: 50%;
  height: 180px;
}

.click-detail view {
  font-size: 18px;
  line-height: 30px;
}

.click-purchase {
  display: flex;
  justify-content: space-between;
}

.click-purchase button {
  width: 48%;
  margin: 0;
  font-size: 16px;
}
</style>

// aplus_taro3x_native/src/pages/click/click.tsx
import React, { Component } from "react";
import Taro from "@tarojs/taro";
import { View, Image, Button } from "@tarojs/components";
import { onAplusClk, record } from "../../utils/aplus_api";
// import "./index.less";

export default class Click extends Component {
  constructor(props: any) {
    super(props);
    this.state = {};
  }

  componentWillMount() {}

  componentDidMount() {}

  componentWillUnmount() {}

  componentDidShow() {}

  componentDidHide() {}

  // 页面分享事件日志上报时，需注册该方法
  onShareAppMessage() {}

  render() {
    return (
      <View className="component">
        <View
          className="container"
          style={{
            display: "flex",
            alignItems: "flex-end",
          }}
        >
          <View
            style={{
              width: "60%",
            }}
          >
            <Image
              style={{ width: "100%" }}
              src="https://gd1.alicdn.com/imgextra/i4/2207297515629/O1CN01W5rDzt1rS89qNHD1f_!!2207297515629.jpg_400x400.jpg"
            ></Image>
          </View>
          <View
            style={{
              width: "40%",
            }}
          >
            <View>商品名称: 床头灯</View>
            <View>颜色: 黄色</View>
            <View>商品ID: 003</View>
          </View>
        </View>

        <View style={{ display: "flex" }}>
          <View className="wrapper auto-click" data-product="床头灯1" data-productColor="黄色1" data-productId="id111">
            <Button>点击购买(自动)</Button>
          </View>
          <View className="wrapper">
            <Button
              onClick={() => {
                record("ClickToBuy", "CLK", {
                  product: "床头灯2",
                  productColor: "黄色2",
                  productId: "id222",
                });
              }}
            >
              点击购买(手动)
            </Button>
          </View>
        </View>
      </View>
    );
  }
}
